### ISSUE TITLE
Bot not opening

### ISSUE THREAD

**Issue by henrique2d** [Arcitectus/Sanderling#58]
I used the bot before, it worked out pretty fine, but since i changed the principal monitor(already changed it back) it does not work anymore, opening a blank image in the task bar, and nothing in the desktop
![image](https://user-images.githubusercontent.com/44242795/47109558-f112d900-d224-11e8-9d4a-15591ef83287.png)

**Comment by Viir** [comment]
Sounds like a problem with the placement of the window.

What do you see when you press `Shift` key and right mouse button on the icon in the taskbar to bring up this menu?
![image](https://user-images.githubusercontent.com/19209696/47172033-db231800-d2f9-11e8-9b88-b21913a2e36c.png)

What happens when you maximize the window?

**Comment by henrique2d** [comment]
it worked, thank you very much
