### ISSUE TITLE
Last Measurement

### ISSUE THREAD

**Issue by ChingChickenwing** [Arcitectus/Sanderling#65]
Well hi
I just downloaded Sanderling and wanted to start to use it. It isnt working because "last measurements is till "red x-ed". I put a screenshot here so it is easier to understand. Anyone got an Idea?
![WhyMrSanderling](https://user-images.githubusercontent.com/55287600/64872003-a8d38500-d646-11e9-9f0b-783cf0fc5689.PNG)

**Comment by Viir** [comment]
Maybe memory reading fails because the EVE Online client is configured to `Run clients with 64 bit`.
Can you open this EVE Online configuration dialog?:
![](https://camo.githubusercontent.com/04f8f821c80d25180286f8904e82236bb6ff7bce/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30362f31312f3563666639646531333836636136363031332e706e67)

**Comment by Viir** [comment]
The newest version of Sanderling memory reading now works for the 64-bit game client. As long as you use the latest version, this problem should not occur anymore.

You can download the latest version of the memory reading program from https://github.com/Arcitectus/Sanderling/releases/download/v2020-01-11/2020-01-11.read-memory-64-bit.zip

Also related, the announcement of 64-bit client support: https://forum.botengine.org/t/botengine-devlog/2183/32?u=viir

**Comment by ackurdeeve** [comment]
It seems a little different. I downloaded the src and rebuilt it. The sanderling.exe did not read any parameters from 64bit game.

**Comment by Viir** [comment]
Hello @ackurdeeve, sorry for the confusion, seems the instructions for building from source can be improved.

Building from source works differently since the introduction of the version for 64-bit clients:

+ The software uses .NET core 3.1, download the SDK from https://dotnet.microsoft.com/download/dotnet-core/3.1
+ The source code is contained in the directory [implement/read-memory-64-bit](https://github.com/Arcitectus/Sanderling/tree/master/implement/read-memory-64-bit)
+ You can build it using the `dotnet build` command.

**Comment by ackurdeeve** [comment]
Thanks. I will try that later. Is it the same with the 32bit version that I can observe the memory in realtime? I tried the compiled one，and only get a zip file.

**Comment by Viir** [comment]
Yes you can observe the memory in realtime. You need to get the ID of the game client process to pass it to the memory reading program:
```cmd
read-memory-64-bit.exe read-memory-eve-online --pid=1234
```

On the first run, it outputs the root address of the UI tree. You can than add this to the parameters to skip the step of searching for the UI tree root:
```cmd
read-memory-64-bit.exe read-memory-eve-online --pid=1234 --root-address=0x123456789
```

**Comment by ackurdeeve** [comment]
@Viir I tried, however, the new implementation is very different from the old one. The old measurement is so great. Since I already got used to the tradition method, the new implemention seems more difficult integrating into my code.
